"""Generate the Markdown CLI reference (docs/CLI.md) from the Click tree.

Regenerate after changing any command, option, or help text:

    uv run python -m treqs_cli.reference_docs

tests/test_reference_docs.py fails when docs/CLI.md is stale, so the
reference can never drift from the implementation. Only meaningful from a
source checkout (the docs directory lives next to src/).
"""

from __future__ import annotations

from importlib import import_module
from pathlib import Path

import click

from .cli import cli
from .command_registry import COMMAND_SPECS

REFERENCE_WIDTH = 80
GENERATED_NOTE = (
    "<!-- Generated by `uv run python -m treqs_cli.reference_docs`. Do not edit by hand. -->"
)


def render_reference() -> str:
    parts: list[str] = [
        "# treqs CLI reference",
        "",
        GENERATED_NOTE,
        "",
        _help_section("treqs", cli),
    ]
    for spec in COMMAND_SPECS:
        module = import_module(spec.module_path)
        command = getattr(module, spec.attr_name)
        parts.extend(
            _help_section(path, subcommand)
            for path, subcommand in _walk(f"treqs {spec.name}", command)
        )
    return "\n".join(parts)


def _walk(path: str, command: click.Command) -> list[tuple[str, click.Command]]:
    entries = [(path, command)]
    if isinstance(command, click.Group):
        for name in sorted(command.commands):
            entries.extend(_walk(f"{path} {name}", command.commands[name]))
    return entries


def _help_section(path: str, command: click.Command) -> str:
    ctx = click.Context(command, info_name=path, terminal_width=REFERENCE_WIDTH)
    return f"## `{path}`\n\n```\n{command.get_help(ctx)}\n```\n"


def reference_path() -> Path:
    return Path(__file__).resolve().parents[2] / "docs" / "CLI.md"


def main() -> None:
    path = reference_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_reference(), encoding="utf-8")
    click.echo(f"Wrote {path}")


if __name__ == "__main__":
    main()
